Compile
wmo-im/wmds pull request #321
Opened 2021-06-28 16:30 UTC by amilan17

Compile is a branch of all the issues that are related to table 1-01-01.

2021-06-28 17:21 UTC, amilan17 commented on tables_en/1-01-01.csv
> +310,wind,"Upper wind (X, Y components, horizontal)",Horizontal component of wind as a vector in an orthogonal coordinate system.
#267 - 309 deleted

2021-06-29 08:45 UTC, amilan17 commented
branch not ready for pr

2021-07-12 08:22 UTC, fstuerzl requested changes
Apart from the following issues, the diff looks good. Only these three variables need to be fixed:
- 315, description: Spectral volumetric extinction cross-section of aerosol particles.
- 192, name: CH4 (methane)
- 506, description: Effective depth (thickness) of a cloud from the viewpoint of radiation propagation. Specifically, OD = exp(-K.Δz), where K is the extinction coefficient [km-1] and Δz the vertical path [km] between the base and the top of the cloud. The WMO Cloud Atlas (https://cloudatlas.wmo.int/en/optical-thickness.html) defines cloud optical thickness as 'The optical thickness of a cloud is the degree to which the cloud prevents light from passing through it.'

@amilan17, can I make the corrections myself by editing this branch https://github.com/wmo-im/wmds/blob/compile/tables_en/1-01-01.csv or how does it work?

2021-07-12 09:19 UTC, amilan17 commented
> @amilan17, can I make the corrections myself by editing this branch https://github.com/wmo-im/wmds/blob/compile/tables_en/1-01-01.csv or how does it work?

@fstuerzl -- please do make the corrections in the compile branch! Thanks.

2021-07-12 09:22 UTC, fstuerzl commented
> > @amilan17, can I make the corrections myself by editing this branch https://github.com/wmo-im/wmds/blob/compile/tables_en/1-01-01.csv or how does it work?
> 
> @fstuerzl -- please do make the corrections in the compile branch! Thanks.

Done!

2021-07-13 07:10 UTC, fstuerzl commented
Name of variable 619 fixed: "Sulphate (SO4=), corrected"

2021-07-14 06:45 UTC, joergklausen approved these changes
I have reviewed this to the best of my abilities and it looks okay now.

2021-07-14 08:58 UTC, fstuerzl approved these changes
I have reviewed the table again and didn't find any mistakes.

2021-07-14 15:37 UTC, merged